info:
  contact: { }
  license: { }
paths:
  /api/tags:
    post:
      parameters:
        - description: Name
          in: query
          name: name
          required: true
          type: string
        - description: State
          in: query
          name: state
          type: integer
        - description: CreatedBy
          in: query
          name: created_by
          type: integer
      produces:
        - application/json
      summary: 新增文章标签
  /api/tags/{id}:
    put:
      parameters:
        - description: ID
          in: path
          name: id
          required: true
          type: integer
        - description: ID
          in: query
          name: name
          required: true
          type: string
        - description: State
          in: query
          name: state
          type: integer
        - description: ModifiedBy
          in: query
          name: modified_by
          required: true
          type: string
      produces:
        - application/json
      summary: 修改文章标签
swagger: "2.0"
