[server]
name = "demo-chatroom"
addr = ":8888"

[server.logger]
level = "debug"

# 数据库相关
[database]
driver = "mysql"

[mysql]
dbHost = "localhost"
dbPort = "3306"
dbName = "class-room"
dbParams = "parseTime=true&loc=Local"
dbUser = "root"
dbPasswd = "root"